# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee2d5ff4a45166c4b08a1b179e641f1a37649838b6dfe7f0b002e7b9751414c420276a0704dd4a9f40edfb5ffcdadb16df759f4e9212b186fe298ab71d8af58a

test:
  secret_key_base: 458fe8abd0c196322a4cb4a71d1046b03c94eb8cb6959402f26039577ad3118433851565b19912af6e06f76ed46ff67abd96f84872ab63dc717c612cb6f2dee7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
